# Generated by Django 4.1.3 on 2024-02-22 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MilitarIncluso",
            fields=[
                (
                    "RE",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("id", models.CharField(max_length=6)),
                ("posto_graduacao", models.CharField(max_length=100)),
                ("nome", models.CharField(max_length=255)),
                ("adicionais", models.IntegerField()),
                ("dependentes", models.IntegerField()),
                (
                    "sexta_parte",
                    models.CharField(
                        choices=[("SIM", "Sim"), ("NAO", "Não")], max_length=3
                    ),
                ),
                (
                    "hora_aula",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("data_agregacao", models.DateField()),
                ("data_saida", models.DateField(blank=True, null=True)),
                ("oficio_dp", models.CharField(max_length=100)),
                (
                    "mes_referencia",
                    models.CharField(
                        choices=[
                            ("Jan", "Janeiro"),
                            ("Fev", "Fevereiro"),
                            ("Mar", "Março"),
                            ("Abr", "Abril"),
                            ("Mai", "Maio"),
                            ("Jun", "Junho"),
                            ("Jul", "Julho"),
                            ("Ago", "Agosto"),
                            ("Set", "Setembro"),
                            ("Out", "Outubro"),
                            ("Nov", "Novembro"),
                            ("Dez", "Dezembro"),
                        ],
                        max_length=3,
                    ),
                ),
                ("pag_a_contar_de", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Beneficiario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("cpf", models.CharField(max_length=11)),
                ("agencia_cc", models.CharField(max_length=100)),
                ("cota", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "militar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="militares.militarincluso",
                    ),
                ),
            ],
        ),
    ]
