# Generated by Django 4.1.3 on 2024-02-22 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="beneficiario", name="id",),
        migrations.RemoveField(model_name="militarincluso", name="id",),
        migrations.AlterField(
            model_name="beneficiario",
            name="militar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="militares.militarincluso",
                unique=True,
            ),
        ),
    ]
