# Generated by Django 4.1.3 on 2024-02-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0002_remove_beneficiario_id_remove_militarincluso_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="militarincluso",
            name="posto_graduacao",
            field=models.CharField(
                choices=[
                    ("Sd PM 2ºCL", "Sd PM 2ºCL"),
                    ("Sd PM 1ºCL", "Sd PM 1ºCL"),
                    ("Cb PM", "Cb PM"),
                    ("3º Sgt PM", "3º Sgt PM"),
                    ("2º Sgt PM", "2º Sgt PM"),
                    ("1º Sgt PM", "1º Sgt PM"),
                    ("SubTen PM", "SubTen PM"),
                    ("Al CFO 1º Ano", "Al CFO 1º Ano"),
                    ("Al CFO 2º Ano", "Al CFO 2º Ano"),
                    ("Al CFO 3º Ano", "Al CFO 3º Ano"),
                    ("Al CFO 4º Ano", "Al CFO 4º Ano"),
                    ("AspTen PM", "AspTen PM"),
                    ("2º Ten PM", "2º Ten PM"),
                    ("1º Ten PM", "1º Ten PM"),
                    ("Cap Ten PM", "Cap Ten PM"),
                    ("Maj Ten PM", "Maj Ten PM"),
                    ("TenCel PM", "TenCel PM"),
                    ("Cel PM", "Cel PM"),
                ],
                max_length=100,
            ),
        ),
    ]
