# Generated by Django 4.1.3 on 2024-02-27 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "militares",
            "0004_alter_beneficiario_cpf_alter_beneficiario_militar_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="beneficiario", unique_together=set(),),
        migrations.AlterField(
            model_name="beneficiario",
            name="cpf",
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name="beneficiario",
            name="militar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="militares.militarincluso",
            ),
        ),
    ]
