# Generated by Django 4.1.3 on 2024-02-27 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0005_alter_beneficiario_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beneficiario",
            name="militar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="militares.militarincluso",
                unique=True,
            ),
        ),
    ]
