# Generated by Django 4.1.3 on 2024-02-27 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0006_alter_beneficiario_militar"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiario",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="beneficiario",
            name="militar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="militares.militarincluso",
            ),
        ),
    ]
