# Generated by Django 4.1.3 on 2024-02-27 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0008_remove_beneficiario_id_alter_beneficiario_militar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beneficiario",
            name="cpf",
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="beneficiario",
            name="militar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="militares.militarincluso",
            ),
        ),
    ]
