# Generated by Django 4.1.3 on 2024-05-17 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("militares", "0012_memorialdecalculo"),
    ]

    operations = [
        migrations.AlterModelOptions(name="memorialdecalculo", options={},),
        migrations.AlterModelOptions(
            name="tb_vencimentos",
            options={
                "verbose_name": "Memorial de Cálculo",
                "verbose_name_plural": "Memoriais de Cálculo",
            },
        ),
        migrations.AlterField(
            model_name="memorialdecalculo",
            name="outros",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.CreateModel(
            name="OutrosMemorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_campo", models.CharField(max_length=100)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "memorial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outros_campos",
                        to="militares.memorialdecalculo",
                    ),
                ),
            ],
        ),
    ]
